// BeatThisPreprocessorTests — DSP.2 S2 golden tests for Beat This! preprocessor.
//
// Five tests verify BeatThisPreprocessor against Beat This!'s Python LogMelSpect
// (commit 9d787b97). The golden fixture `love_rehab_spect_reference.json` was
// generated by `Scripts/dump_beatthis_spect_reference.py` using the same Python
// implementation. The audio fixture is decoded by ffmpeg at 22050 Hz in the
// `loveRehab_goldenMatch` test to match the Python script's decoding exactly.
//
// Documented tolerance: see docs/diagnostics/DSP.2-architecture.md §2.

import Testing
import Foundation
import AVFoundation
@testable import DSP

@Suite("BeatThisPreprocessor")
struct BeatThisPreprocessorTests {

    // MARK: - 1. Shape (30 s)

    @Test("shape: 30 s silence → (1501, 128)")
    func test_shape_30s() {
        // 30 s at 22050 Hz = 661500 samples. T = 661500/441 + 1 = 1501.
        let samples = [Float](repeating: 0, count: 661500)
        let pp = BeatThisPreprocessor()
        let (data, T) = pp.process(samples: samples)
        #expect(T == 1501)
        #expect(data.count == T * BeatThisPreprocessor.nMels)
    }

    // MARK: - 2. Shape (variable)

    @Test("shape: 1 s silence → (51, 128)")
    func test_shape_variable() {
        // 1 s at 22050 Hz = 22050 samples. T = 22050/441 + 1 = 51.
        let samples = [Float](repeating: 0, count: 22050)
        let pp = BeatThisPreprocessor()
        let (data, T) = pp.process(samples: samples)
        #expect(T == 51)
        #expect(data.count == T * BeatThisPreprocessor.nMels)
    }

    // MARK: - 3. DC signal

    @Test("dcSignal: constant 1.0 → all mel bins == 0.0")
    func test_dcSignal() throws {
        // DC occupies FFT bin 0 only. The Slaney mel filterbank starts at FFT bin 1
        // (f_min=30 Hz maps to bin 1, which has weight 0 at the filter's left edge).
        // Therefore no mel bin receives any energy. log1p(1000 × 0) = 0.
        let samples = [Float](repeating: 1.0, count: 22050)
        let pp = BeatThisPreprocessor()
        let (data, T) = pp.process(samples: samples)
        #expect(T > 0)
        #expect(data.count == T * BeatThisPreprocessor.nMels)
        let maxVal = data.max() ?? 0
        // Threshold 0.01: float32 FFT noise on 1024-pt Hann-windowed DC ≈ 5e-4.
        // Any correct implementation yields maxVal << 1 (real audio signals give values 0.5-7).
        #expect(maxVal < 0.01, "DC signal should produce near-zero mel output, got max=\(maxVal)")
    }

    // MARK: - 4. Sine at mel bin

    @Test("sineAtMelBin: 440 Hz sine → max mel energy > 1.0")
    func test_sineAtMelBin() {
        // A 440 Hz sine at 22050 Hz lands near FFT bin 20 (440 × 1024/22050 ≈ 20.4).
        // That bin is covered by mel filter ~16 (mel(440 Hz) ≈ 6.6 mel, ~index 16).
        // log1p(1000 × mel_energy) for a unit-amplitude sine must be >> 1.0.
        let sr: Float = 22050
        let freq: Float = 440
        let samples = (0..<22050).map { n -> Float in
            sin(2 * Float.pi * freq * Float(n) / sr)
        }
        let pp = BeatThisPreprocessor()
        let (data, T) = pp.process(samples: samples)
        #expect(T > 0)
        let maxVal = data.max() ?? 0
        #expect(maxVal > 1.0, "440 Hz sine should excite at least one mel bin strongly, got max=\(maxVal)")
    }

    // MARK: - 5. Love Rehab golden match

    @Test("loveRehab: first 10 frames match Python reference within tolerance")
    func test_loveRehab_goldenMatch() throws {
        // Find audio: Tests/Fixtures/tempo/love_rehab.m4a (relative to this source file).
        // #filePath gives the absolute path to this source file at compile time.
        let testDir = URL(fileURLWithPath: String(#filePath)).deletingLastPathComponent()
        let audioURL = testDir
            .deletingLastPathComponent()  // PhospheneEngineTests/
            .deletingLastPathComponent()  // Tests/
            .appendingPathComponent("Fixtures/tempo/love_rehab.m4a")
        // Debug: uncomment to diagnose path issues.
        // print("BeatThisPreprocessorTests: audioURL=\(audioURL.path)")

        guard FileManager.default.fileExists(atPath: audioURL.path) else {
            // Fixture not available (e.g. CI without audio assets) — skip gracefully.
            print("BeatThisPreprocessorTests: skipping loveRehab_goldenMatch (fixture absent)")
            return
        }

        // Decode via ffmpeg at 22050 Hz mono to match Python script exactly.
        let samples = try decodeMono22050HzViaFfmpeg(url: audioURL)
        #expect(samples.count > 10_000, "Expected significant audio, got \(samples.count) samples")

        // Run preprocessor
        let pp = BeatThisPreprocessor()
        let (data, T) = pp.process(samples: samples, inputSampleRate: 22050)
        #expect(T >= 10, "Expected at least 10 frames, got \(T)")

        // Load Python reference from bundle
        let refURL = try #require(
            Bundle.module.url(
                forResource: "love_rehab_spect_reference",
                withExtension: "json",
                subdirectory: "beat_this_reference"
            ),
            "love_rehab_spect_reference.json not found in bundle"
        )
        let refData = try Data(contentsOf: refURL)
        let ref = try JSONDecoder().decode(SpectReference.self, from: refData)

        // Compare first 10 frames bin-by-bin.
        // Tolerance 1e-3: actual observed max|Δ|≈3e-5 (vDSP vs PyTorch float32 rounding).
        // Documented in docs/diagnostics/DSP.2-architecture.md §2.
        let tolerance: Float = 1e-3
        var maxDelta: Float = 0
        var firstFailure: String?

        for frame in 0..<ref.nReferenceFrames {
            for bin in 0..<BeatThisPreprocessor.nMels {
                let swiftVal = data[frame * BeatThisPreprocessor.nMels + bin]
                let pythonVal = Float(ref.frames10x128[frame][bin])
                let delta = abs(swiftVal - pythonVal)
                if delta > maxDelta { maxDelta = delta }
                if delta > tolerance && firstFailure == nil {
                    firstFailure = "frame=\(frame) bin=\(bin): swift=\(swiftVal) python=\(pythonVal) delta=\(delta)"
                }
            }
        }

        print("BeatThisPreprocessorTests: loveRehab max|Δ|=\(maxDelta) tolerance=\(tolerance)")

        if let fail = firstFailure {
            #expect(Bool(false), "Golden match exceeded tolerance: \(fail)")
        }
    }

    // MARK: - Helpers

    /// Decode audio to mono Float32 at 22050 Hz via ffmpeg subprocess.
    /// Matches the decoding in Scripts/dump_beatthis_spect_reference.py exactly.
    private func decodeMono22050HzViaFfmpeg(url: URL) throws -> [Float] {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "ffmpeg", "-i", url.path,
            "-ac", "1", "-ar", "22050",
            "-f", "f32le", "-", "-loglevel", "error"
        ]
        let stdoutPipe = Pipe()
        let stderrPipe = Pipe()
        process.standardOutput = stdoutPipe
        process.standardError = stderrPipe

        try process.run()
        let rawData = stdoutPipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            let errMsg = String(data: stderrPipe.fileHandleForReading.readDataToEndOfFile(),
                               encoding: .utf8) ?? ""
            throw NSError(domain: "BeatThisPreprocessorTests",
                          code: Int(process.terminationStatus),
                          userInfo: [NSLocalizedDescriptionKey: "ffmpeg failed: \(errMsg)"])
        }

        let count = rawData.count / MemoryLayout<Float>.size
        return rawData.withUnsafeBytes { ptr in
            Array(ptr.bindMemory(to: Float.self).prefix(count))
        }
    }

    // MARK: - Decodable reference type

    private struct SpectReference: Decodable {
        let nReferenceFrames: Int
        let frames10x128: [[Double]]

        enum CodingKeys: String, CodingKey {
            case nReferenceFrames = "n_reference_frames"
            case frames10x128 = "frames_10x128"
        }
    }
}
