#!/usr/bin/env swift
// generate_dsp_fixtures.swift — Generate golden test fixtures for DSP regression tests.
// Run from the project root: swift tools/generate_dsp_fixtures.swift
//
// Generates:
//   PhospheneEngine/Tests/PhospheneEngineTests/Regression/Fixtures/c_major_chord_4800.json
//   PhospheneEngine/Tests/PhospheneEngineTests/Regression/Fixtures/120bpm_kick_48000.json
//
// The chroma and onset golden values are generated by running the actual DSP code
// and captured separately (see regression tests).

import Foundation

let fixturesDir = "PhospheneEngine/Tests/PhospheneEngineTests/Regression/Fixtures"

// MARK: - C Major Chord (4800 samples)

func generateCMajorChord() -> [Double] {
    let sampleRate: Double = 48000
    let sampleCount = 4800  // 0.1 seconds
    // C5=523.25, E5=659.25, G5=783.99 Hz
    let frequencies: [Double] = [523.25, 659.25, 783.99]

    var samples = [Double](repeating: 0, count: sampleCount)
    for freq in frequencies {
        let omega = 2.0 * Double.pi * freq / sampleRate
        for i in 0..<sampleCount {
            samples[i] += sin(omega * Double(i)) / Double(frequencies.count)
        }
    }
    return samples
}

// MARK: - 120 BPM Kick Pattern (48000 samples = 1 second)

func generate120BPMKick() -> [Double] {
    let sampleRate: Double = 48000
    let sampleCount = 48000  // 1 second
    let bpm: Double = 120
    let beatInterval = sampleRate * 60.0 / bpm  // samples per beat

    var samples = [Double](repeating: 0, count: sampleCount)

    // Generate kicks: short low-frequency burst at each beat.
    let kickDuration = 200  // samples (~4ms)
    let kickFreq: Double = 60.0  // Hz

    var nextKick: Double = 0
    while Int(nextKick) < sampleCount {
        let startSample = Int(nextKick)
        for i in 0..<kickDuration {
            let idx = startSample + i
            guard idx < sampleCount else { break }
            let t = Double(i) / sampleRate
            // Exponentially decaying sine burst.
            let envelope = exp(-t * 50.0)
            samples[idx] += sin(2.0 * Double.pi * kickFreq * t) * envelope
        }
        nextKick += beatInterval
    }
    return samples
}

// MARK: - Write JSON

func writeJSON(_ values: [Double], filename: String) {
    let json = "[\n" + values.map { String(format: "  %.10f", $0) }.joined(separator: ",\n") + "\n]"
    let path = "\(fixturesDir)/\(filename)"
    do {
        try json.write(toFile: path, atomically: true, encoding: .utf8)
        print("Wrote \(values.count) values to \(path)")
    } catch {
        print("ERROR writing \(path): \(error)")
    }
}

// Generate and write fixtures.
print("Generating DSP regression fixtures...")

let chord = generateCMajorChord()
writeJSON(chord, filename: "c_major_chord_4800.json")

let kick = generate120BPMKick()
writeJSON(kick, filename: "120bpm_kick_48000.json")

print("Done. Now run the regression tests to capture golden values.")
